name: Trigger Jenkins Job

on:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job via REST API
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/Devops%20Project/build" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}"
