name: TODO APP

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Deploy to Tomcat
      if: success()  # Only runs if build and tests pass
      run: |
        curl -v -u ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }} \
        -T target/YOUR_PROJECT.war \
        "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/YOUR_PROJECT&update=true"
